kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  namespace: nfs-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-provisioner/nfs-ssd1
            - name: NFS_SERVER
              value: 192.168.24.20
            - name: NFS_PATH
              value: /mnt/hd1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nfs-client-provisioner
              topologyKey: kubernetes.io/hostname

      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.24.20
            path: /mnt/hd1
